"""Shared utilities for UOP data-processing workflows."""

from .coare import (
    add_scalar_input_variable,
    apply_current_relative_wind,
    annotate_reference_height_outputs,
    ensure_1d,
    instrument_prefix_for_var,
    load_processing_config,
    pick_instrument_height,
    process_radiation,
    process_surface_current,
    resample_dataset,
    to_scalar,
    write_coare_scalar_latex_table,
)
from .geo import (
    calculate_angle_between_vectors,
    calculate_wind_stress_components,
    circular_mean_resample,
    compute_current_relative_wind,
    is_directional_variable,
    vector_to_met_direction,
)
from .io import create_dir, load_config, update_encoding, write_json
from .metadata import (
    add_metadata_comments,
    append_history,
    build_data_array,
    compute_practical_salinity_from_conductivity,
    fix_waveglider_issues,
    fix_L2_metadata,
    get_git_provenance_info,
    get_uop_coare_details,
    get_uop_coare_version,
    get_uop_utils_details,
    validate_time_range,
    write_git_provenance,
)
from .naming import extract_campaign_names
from .plotting import (
    build_gap_aware_series,
    create_custom_figure_latex,
    create_figure_latex,
    create_two_figure_page_latex,
    format_compact_date_labels,
    plot_coare_input_multipanel,
)
from .qc import apply_nortek_qc_flags, apply_qc_flags, apply_workhorse_qc_flags, remove_spikes

__all__ = [
    'add_metadata_comments',
    'add_scalar_input_variable',
    'apply_current_relative_wind',
    'annotate_reference_height_outputs',
    'build_gap_aware_series',
    'build_data_array',
    'calculate_angle_between_vectors',
    'compute_practical_salinity_from_conductivity',
    'calculate_wind_stress_components',
    'circular_mean_resample',
    'compute_current_relative_wind',
    'create_custom_figure_latex',
    'create_dir',
    'load_config',
    'create_figure_latex',
    'create_two_figure_page_latex',
    'ensure_1d',
    'extract_campaign_names',
    'fix_L2_metadata',
    'format_compact_date_labels',
    'plot_coare_input_multipanel',
    'append_history',
    'fix_waveglider_issues',
    'get_git_provenance_info',
    'get_uop_coare_details',
    'get_uop_coare_version',
    'get_uop_utils_details',
    'instrument_prefix_for_var',
    'is_directional_variable',
    'load_processing_config',
    'pick_instrument_height',
    'process_radiation',
    'process_surface_current',
    'apply_nortek_qc_flags',
    'apply_qc_flags',
    'apply_workhorse_qc_flags',
    'remove_spikes',
    'resample_dataset',
    'to_scalar',
    'update_encoding',
    'validate_time_range',
    'vector_to_met_direction',
    'write_coare_scalar_latex_table',
    'write_json',
    'write_git_provenance',
]

__version__ = '1.0.2'
